# ==========================================
# Tmux Litte Config (No Plugins)
# ==========================================

# ==========================================
# Keybindings and Refresh
# ==========================================
unbind r
bind r source-file ~/.tmux.rreji.conf \; display-message "Lite config reloaded"
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind | split-window -h
bind - split-window -v

# ==========================================
# SSH Passthrough Toggle (Alt + Z)
# ==========================================
bind -T root M-z \
    set prefix None \;\
    set key-table off \;\
    set status-style "fg=gray,bg=black" \;\
    display-message "Local tmux disabled (Passthrough ON)"

bind -T off M-z \
    set -u prefix \;\
    set -u key-table \;\
    set -u status-style \;\
    display-message "Local tmux enabled (Passthrough OFF)"

# ==========================================
# Window Appearance
# ==========================================
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# ==========================================
# General
# ==========================================
set -g prefix C-s
set -sg escape-time 0
set -g mouse on
set -g base-index 1
set -g renumber-windows on

# ==========================================
# Window & Native Status Bar
# ==========================================
set-window-option -g mode-keys vi
set -g status-style bg=default
set-option -g status-position top
set-option -g automatic-rename-format "#{b:pane_current_path}"
set-option -g automatic-rename on

set -g status-left-length 40
set -g status-left "#[fg=green,bold][#S] "
set -g status-right "#[fg=yellow]%H:%M #[fg=blue]%d-%b-%y"
