# ==========================================
# Keybings and Refresh
# ==========================================
unbind r
bind r source-file ~/.tmux.conf
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind | split-window -h
bind - split-window -v

# ==========================================
# Window Appearance
# ==========================================
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# ==========================================
# General
# ==========================================
set -g prefix C-s
set -sg escape-time 0
set -g mouse on

# ==========================================
# Window
# ==========================================
set-window-option -g mode-keys vi
set -g status-style bg=default
set-option -g status-position top

set -g @smooth-scroll-speed "100"
set -g @smooth-scroll-easing "sine"
set -g @smooth-scroll-mouse "true"
set -g @smooth-scroll-normal "3"
set -g @smooth-scroll-exit-copy-mode-at-bottom "true"

# set -g @catppuccin_window_default_text " #W"
# set -g @catppuccin_window_text " #W"
# set -g @catppuccin_window_current_text " #W"

set -g @catppuccin_window_default_text " #{b:pane_current_path}"
set -g @catppuccin_window_text " #{b:pane_current_path}"
set -g @catppuccin_window_current_text " #{b:pane_current_path}#{?window_zoomed_flag,  ,}"

# ==========================================
# Catppuccin 
# ==========================================
set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_window_status_style "rounded"
run ~/.tmux/plugins/tmux/catppuccin.tmux

# ==========================================
# Resurrect + Continuum settings 
# ==========================================
# Resurrect settings
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-processes 'btop yazi htop "~nvim"'
set -g @resurrect-strategy-vim 'session'

# Continuum settings
set -g @continuum-restore 'on' # Automatically restore tmux windows
set -g @continuum-save-interval '15' # Save in minutes

# ==========================================
# Apply status bar configs
# ==========================================
set -g status-right-length 100
set -g status-left-length 100
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# ==========================================
# Plugins
# ==========================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'azorng/tmux-smooth-scroll'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'xamut/tmux-spotify' # TODO: uses C-s, how to change?

# ==========================================
# Run plugins
# ==========================================
run '~/.tmux/plugins/tmux-cpu/cpu.tmux'
run '~/.tmux/plugins/tpm/tpm'
