# ==========================================
# Keybings and Refresh
# ==========================================
unbind r
bind r source-file ~/.tmux.conf
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind | split-window -h
bind - split-window -v

# ==========================================
# Window Appearance
# ==========================================
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# ==========================================
# General
# ==========================================
set -g prefix C-s
set -sg escape-time 0
set -g mouse on

# ==========================================
# Window
# ==========================================
set-window-option -g mode-keys vi
set -g status-style bg=default
set-option -g status-position top
# set -g @catppuccin_window_default_text " #W"
# set -g @catppuccin_window_text " #W"
# set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_default_text " #{b:pane_current_path}"
set -g @catppuccin_window_text " #{b:pane_current_path}"
set -g @catppuccin_window_current_text " #{b:pane_current_path}#{?window_zoomed_flag,  ,}"

# ==========================================
# Plugins
# ==========================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'tmux-plugins/tmux-cpu'

# ==========================================
# Catppuccin 
# ==========================================
set -g @catppuccin_flavor 'macchiato'
run ~/.tmux/plugins/tmux/catppuccin.tmux

# ==========================================
# Apply status bar configs
# ==========================================
set -g status-right-length 100
set -g status-left-length 100
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# ==========================================
# Run plugins
# ==========================================
run ~/.tmux/plugins/tmux-cpu/cpu.tmux
run '~/.tmux/plugins/tpm/tpm'
